[package]
name = "pinv_2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.11", features = ["derive"] }
clap-stdin = "0.3.0"
clap_complete = "4.4.4"
itertools = "0.12.0"
